INSERT INTO statemodel  VALUES (1, 'AL','Alabama');
INSERT INTO statemodel  VALUES (2, 'AK','Alaska');
INSERT INTO statemodel  VALUES (3, 'AS','American Samoa');
INSERT INTO statemodel  VALUES (4, 'AZ','Arizona');
INSERT INTO statemodel  VALUES (5, 'AR','Arkansas');
INSERT INTO statemodel  VALUES (6, 'CA','California');
INSERT INTO statemodel  VALUES (7, 'CO','Colorado');
INSERT INTO statemodel  VALUES (8, 'CT','Connecticut');
INSERT INTO statemodel  VALUES (9, 'DE','Delaware');
INSERT INTO statemodel  VALUES (10, 'DC','District of Columbia');
INSERT INTO statemodel  VALUES (11, 'FM','Federated States of Micronesia');
INSERT INTO statemodel  VALUES (12, 'FL','Florida');
INSERT INTO statemodel  VALUES (13, 'GA','Georgia');
INSERT INTO statemodel  VALUES (14, 'GU','Guam');
INSERT INTO statemodel  VALUES (15, 'HI','Hawaii');
INSERT INTO statemodel  VALUES (16, 'ID','Idaho');
INSERT INTO statemodel  VALUES (17, 'IL','Illinois');
INSERT INTO statemodel  VALUES (18, 'IN','Indiana');
INSERT INTO statemodel  VALUES (19, 'IA','Iowa');
INSERT INTO statemodel  VALUES (20, 'KS','Kansas');
INSERT INTO statemodel  VALUES (21, 'KY','Kentucky');
INSERT INTO statemodel  VALUES (22, 'LA','Louisiana');
INSERT INTO statemodel  VALUES (23, 'ME','Maine');
INSERT INTO statemodel  VALUES (24, 'MH','Marshall Islands');
INSERT INTO statemodel  VALUES (25, 'MD','Maryland');
INSERT INTO statemodel  VALUES (26, 'MA','Massachusetts');
INSERT INTO statemodel  VALUES (27, 'MI','Michigan');
INSERT INTO statemodel  VALUES (28, 'MN','Minnesota');
INSERT INTO statemodel  VALUES (29, 'MS','Mississippi');
INSERT INTO statemodel  VALUES (30, 'MO','Missouri');
INSERT INTO statemodel  VALUES (31, 'MT','Montana');
INSERT INTO statemodel  VALUES (32, 'NE','Nebraska');
INSERT INTO statemodel  VALUES (33, 'NV','Nevada');
INSERT INTO statemodel  VALUES (34, 'NH','New Hampshire');
INSERT INTO statemodel  VALUES (35, 'NJ','New Jersey');
INSERT INTO statemodel  VALUES (36, 'NM','New Mexico');
INSERT INTO statemodel  VALUES (37, 'NY','New York');
INSERT INTO statemodel  VALUES (38, 'NC','North Carolina');
INSERT INTO statemodel  VALUES (39, 'ND','North Dakota');
INSERT INTO statemodel  VALUES (40, 'MP','Northern Mariana Islands');
INSERT INTO statemodel  VALUES (41, 'OH','Ohio');
INSERT INTO statemodel  VALUES (42, 'OK','Oklahoma');
INSERT INTO statemodel  VALUES (43, 'OR','Oregon');
INSERT INTO statemodel  VALUES (44, 'PW','Palau');
INSERT INTO statemodel  VALUES (45, 'PA','Pennsylvania');
INSERT INTO statemodel  VALUES (46, 'PR','Puerto Rico');
INSERT INTO statemodel  VALUES (47, 'RI','Rhode Island');
INSERT INTO statemodel  VALUES (48, 'SC','South Carolina');
INSERT INTO statemodel  VALUES (49, 'SD','South Dakota');
INSERT INTO statemodel  VALUES (50, 'TN','Tennessee');
INSERT INTO statemodel  VALUES (51, 'TX','Texas');
INSERT INTO statemodel  VALUES (52, 'UT','Utah');
INSERT INTO statemodel  VALUES (53, 'VT','Vermont');
INSERT INTO statemodel  VALUES (54, 'VI','Virgin Islands');
INSERT INTO statemodel  VALUES (55, 'VA','Virginia');
INSERT INTO statemodel  VALUES (56, 'WA','Washington');
INSERT INTO statemodel  VALUES (57, 'WV','West Virginia');
INSERT INTO statemodel  VALUES (58, 'WI','Wisconsin');
INSERT INTO statemodel  VALUES (59, 'WY','Wyoming');